version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Execute bash script
          command: bash /Users/petezelinski/Applications/demo/hello-World.sh
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
